<?xml version="1.0"?>

<!DOCTYPE NISTXMLSchemaTypeTests [

<!ELEMENT NISTXMLSchemaTypeTests (Type)>

  <!ATTLIST NISTXMLSchemaTypeTests xml:base CDATA #REQUIRED>

<!ELEMENT Type (Notes, Facet*)>

  <!ATTLIST Type Name CDATA #REQUIRED>
  <!ATTLIST Type href CDATA #REQUIRED>

<!ELEMENT Notes (#PCDATA)>

<!ELEMENT Facet (Notes, Schema*)>

  <!ATTLIST Facet Name CDATA #REQUIRED>
  <!ATTLIST Facet href CDATA #REQUIRED>

<!ELEMENT Schema (Notes, Instance*)>

  <!ATTLIST Schema name CDATA #REQUIRED>
  <!ATTLIST Schema href CDATA #REQUIRED>

<!ELEMENT Instance (Notes)>

  <!ATTLIST Instance name CDATA #REQUIRED>
  <!ATTLIST Instance href CDATA #REQUIRED>

]>

<NISTXMLSchemaTypeTests xml:base="">

<Type Name="nonNegativeInteger" href="http://www.w3.org/TR/2001/REC-xmlschema-2-20010502/#nonNegativeInteger">

<Notes>
The value space of type nonNegativeInteger used in these tests is
actually a subset of that defined in the Recommendation. The local
nonNegativeInteger type behaves as if it were derived from the general
type by restriction with totalDigits == 20.

This constraint applies to nonNegativeInteger and all its derivatives,
in the absence of further constraints.

</Notes>

<Facet Name="minExclusive" href="http://www.w3.org/TR/2001/REC-xmlschema-2-20010502/#rf-minExclusive">

<Notes>

</Notes>

<Schema  name="NISTSchema-nonNegativeInteger-minExclusive-1" href="NISTSchema-nonNegativeInteger-minExclusive-1.xsd">

<Notes>
      File: NISTSchema-nonNegativeInteger-minExclusive-1.xsd
      This schema specifies a datatype, NISTSchema-nonNegativeInteger-minExclusive-1,
      which is derived by restriction of built-in type nonNegativeInteger
      by facet minExclusive with a value of: 0

</Notes>

<Instance  name="NISTXML-nonNegativeInteger-minExclusive-1-1" href="NISTXML-nonNegativeInteger-minExclusive-1-1.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minExclusive-1-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minExclusive-1.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minExclusive-1-2" href="NISTXML-nonNegativeInteger-minExclusive-1-2.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minExclusive-1-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minExclusive-1.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minExclusive-1-3" href="NISTXML-nonNegativeInteger-minExclusive-1-3.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minExclusive-1-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minExclusive-1.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minExclusive-1-4" href="NISTXML-nonNegativeInteger-minExclusive-1-4.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minExclusive-1-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minExclusive-1.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minExclusive-1-5" href="NISTXML-nonNegativeInteger-minExclusive-1-5.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minExclusive-1-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minExclusive-1.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-nonNegativeInteger-minExclusive-2" href="NISTSchema-nonNegativeInteger-minExclusive-2.xsd">

<Notes>
      File: NISTSchema-nonNegativeInteger-minExclusive-2.xsd
      This schema specifies a datatype, NISTSchema-nonNegativeInteger-minExclusive-2,
      which is derived by restriction of built-in type nonNegativeInteger
      by facet minExclusive with a value of: 45389918782225913139

</Notes>

<Instance  name="NISTXML-nonNegativeInteger-minExclusive-2-1" href="NISTXML-nonNegativeInteger-minExclusive-2-1.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minExclusive-2-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minExclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minExclusive-2-2" href="NISTXML-nonNegativeInteger-minExclusive-2-2.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minExclusive-2-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minExclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minExclusive-2-3" href="NISTXML-nonNegativeInteger-minExclusive-2-3.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minExclusive-2-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minExclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minExclusive-2-4" href="NISTXML-nonNegativeInteger-minExclusive-2-4.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minExclusive-2-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minExclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minExclusive-2-5" href="NISTXML-nonNegativeInteger-minExclusive-2-5.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minExclusive-2-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minExclusive-2.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-nonNegativeInteger-minExclusive-3" href="NISTSchema-nonNegativeInteger-minExclusive-3.xsd">

<Notes>
      File: NISTSchema-nonNegativeInteger-minExclusive-3.xsd
      This schema specifies a datatype, NISTSchema-nonNegativeInteger-minExclusive-3,
      which is derived by restriction of built-in type nonNegativeInteger
      by facet minExclusive with a value of: 13233459957655535621

</Notes>

<Instance  name="NISTXML-nonNegativeInteger-minExclusive-3-1" href="NISTXML-nonNegativeInteger-minExclusive-3-1.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minExclusive-3-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minExclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minExclusive-3-2" href="NISTXML-nonNegativeInteger-minExclusive-3-2.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minExclusive-3-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minExclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minExclusive-3-3" href="NISTXML-nonNegativeInteger-minExclusive-3-3.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minExclusive-3-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minExclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minExclusive-3-4" href="NISTXML-nonNegativeInteger-minExclusive-3-4.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minExclusive-3-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minExclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minExclusive-3-5" href="NISTXML-nonNegativeInteger-minExclusive-3-5.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minExclusive-3-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minExclusive-3.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-nonNegativeInteger-minExclusive-4" href="NISTSchema-nonNegativeInteger-minExclusive-4.xsd">

<Notes>
      File: NISTSchema-nonNegativeInteger-minExclusive-4.xsd
      This schema specifies a datatype, NISTSchema-nonNegativeInteger-minExclusive-4,
      which is derived by restriction of built-in type nonNegativeInteger
      by facet minExclusive with a value of: 30203263381174283441

</Notes>

<Instance  name="NISTXML-nonNegativeInteger-minExclusive-4-1" href="NISTXML-nonNegativeInteger-minExclusive-4-1.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minExclusive-4-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minExclusive-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minExclusive-4-2" href="NISTXML-nonNegativeInteger-minExclusive-4-2.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minExclusive-4-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minExclusive-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minExclusive-4-3" href="NISTXML-nonNegativeInteger-minExclusive-4-3.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minExclusive-4-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minExclusive-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minExclusive-4-4" href="NISTXML-nonNegativeInteger-minExclusive-4-4.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minExclusive-4-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minExclusive-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minExclusive-4-5" href="NISTXML-nonNegativeInteger-minExclusive-4-5.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minExclusive-4-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minExclusive-4.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-nonNegativeInteger-minExclusive-5" href="NISTSchema-nonNegativeInteger-minExclusive-5.xsd">

<Notes>
      File: NISTSchema-nonNegativeInteger-minExclusive-5.xsd
      This schema specifies a datatype, NISTSchema-nonNegativeInteger-minExclusive-5,
      which is derived by restriction of built-in type nonNegativeInteger
      by facet minExclusive with a value of: 99999999999999999998

</Notes>

<Instance  name="NISTXML-nonNegativeInteger-minExclusive-5-1" href="NISTXML-nonNegativeInteger-minExclusive-5-1.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minExclusive-5-1.xml
      XML instance number 1 in a series of 
      1 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minExclusive-5.xsd.

</Notes>


</Instance>


</Schema>


</Facet>

<Facet Name="minInclusive" href="http://www.w3.org/TR/2001/REC-xmlschema-2-20010502/#rf-minInclusive">

<Notes>

</Notes>

<Schema  name="NISTSchema-nonNegativeInteger-minInclusive-1" href="NISTSchema-nonNegativeInteger-minInclusive-1.xsd">

<Notes>
      File: NISTSchema-nonNegativeInteger-minInclusive-1.xsd
      This schema specifies a datatype, NISTSchema-nonNegativeInteger-minInclusive-1,
      which is derived by restriction of built-in type nonNegativeInteger
      by facet minInclusive with a value of: 0

</Notes>

<Instance  name="NISTXML-nonNegativeInteger-minInclusive-1-1" href="NISTXML-nonNegativeInteger-minInclusive-1-1.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minInclusive-1-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minInclusive-1.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minInclusive-1-2" href="NISTXML-nonNegativeInteger-minInclusive-1-2.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minInclusive-1-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minInclusive-1.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minInclusive-1-3" href="NISTXML-nonNegativeInteger-minInclusive-1-3.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minInclusive-1-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minInclusive-1.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minInclusive-1-4" href="NISTXML-nonNegativeInteger-minInclusive-1-4.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minInclusive-1-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minInclusive-1.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minInclusive-1-5" href="NISTXML-nonNegativeInteger-minInclusive-1-5.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minInclusive-1-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minInclusive-1.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-nonNegativeInteger-minInclusive-2" href="NISTSchema-nonNegativeInteger-minInclusive-2.xsd">

<Notes>
      File: NISTSchema-nonNegativeInteger-minInclusive-2.xsd
      This schema specifies a datatype, NISTSchema-nonNegativeInteger-minInclusive-2,
      which is derived by restriction of built-in type nonNegativeInteger
      by facet minInclusive with a value of: 88812455549057300884

</Notes>

<Instance  name="NISTXML-nonNegativeInteger-minInclusive-2-1" href="NISTXML-nonNegativeInteger-minInclusive-2-1.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minInclusive-2-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minInclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minInclusive-2-2" href="NISTXML-nonNegativeInteger-minInclusive-2-2.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minInclusive-2-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minInclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minInclusive-2-3" href="NISTXML-nonNegativeInteger-minInclusive-2-3.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minInclusive-2-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minInclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minInclusive-2-4" href="NISTXML-nonNegativeInteger-minInclusive-2-4.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minInclusive-2-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minInclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minInclusive-2-5" href="NISTXML-nonNegativeInteger-minInclusive-2-5.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minInclusive-2-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minInclusive-2.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-nonNegativeInteger-minInclusive-3" href="NISTSchema-nonNegativeInteger-minInclusive-3.xsd">

<Notes>
      File: NISTSchema-nonNegativeInteger-minInclusive-3.xsd
      This schema specifies a datatype, NISTSchema-nonNegativeInteger-minInclusive-3,
      which is derived by restriction of built-in type nonNegativeInteger
      by facet minInclusive with a value of: 67816630727910343078

</Notes>

<Instance  name="NISTXML-nonNegativeInteger-minInclusive-3-1" href="NISTXML-nonNegativeInteger-minInclusive-3-1.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minInclusive-3-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minInclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minInclusive-3-2" href="NISTXML-nonNegativeInteger-minInclusive-3-2.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minInclusive-3-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minInclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minInclusive-3-3" href="NISTXML-nonNegativeInteger-minInclusive-3-3.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minInclusive-3-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minInclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minInclusive-3-4" href="NISTXML-nonNegativeInteger-minInclusive-3-4.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minInclusive-3-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minInclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minInclusive-3-5" href="NISTXML-nonNegativeInteger-minInclusive-3-5.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minInclusive-3-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minInclusive-3.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-nonNegativeInteger-minInclusive-4" href="NISTSchema-nonNegativeInteger-minInclusive-4.xsd">

<Notes>
      File: NISTSchema-nonNegativeInteger-minInclusive-4.xsd
      This schema specifies a datatype, NISTSchema-nonNegativeInteger-minInclusive-4,
      which is derived by restriction of built-in type nonNegativeInteger
      by facet minInclusive with a value of: 41063529153863720377

</Notes>

<Instance  name="NISTXML-nonNegativeInteger-minInclusive-4-1" href="NISTXML-nonNegativeInteger-minInclusive-4-1.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minInclusive-4-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minInclusive-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minInclusive-4-2" href="NISTXML-nonNegativeInteger-minInclusive-4-2.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minInclusive-4-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minInclusive-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minInclusive-4-3" href="NISTXML-nonNegativeInteger-minInclusive-4-3.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minInclusive-4-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minInclusive-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minInclusive-4-4" href="NISTXML-nonNegativeInteger-minInclusive-4-4.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minInclusive-4-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minInclusive-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-minInclusive-4-5" href="NISTXML-nonNegativeInteger-minInclusive-4-5.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minInclusive-4-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minInclusive-4.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-nonNegativeInteger-minInclusive-5" href="NISTSchema-nonNegativeInteger-minInclusive-5.xsd">

<Notes>
      File: NISTSchema-nonNegativeInteger-minInclusive-5.xsd
      This schema specifies a datatype, NISTSchema-nonNegativeInteger-minInclusive-5,
      which is derived by restriction of built-in type nonNegativeInteger
      by facet minInclusive with a value of: 99999999999999999999

</Notes>

<Instance  name="NISTXML-nonNegativeInteger-minInclusive-5-1" href="NISTXML-nonNegativeInteger-minInclusive-5-1.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-minInclusive-5-1.xml
      XML instance number 1 in a series of 
      1 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-minInclusive-5.xsd.

</Notes>


</Instance>


</Schema>


</Facet>

<Facet Name="maxExclusive" href="http://www.w3.org/TR/2001/REC-xmlschema-2-20010502/#rf-maxExclusive">

<Notes>

</Notes>

<Schema  name="NISTSchema-nonNegativeInteger-maxExclusive-1" href="NISTSchema-nonNegativeInteger-maxExclusive-1.xsd">

<Notes>
      File: NISTSchema-nonNegativeInteger-maxExclusive-1.xsd
      This schema specifies a datatype, NISTSchema-nonNegativeInteger-maxExclusive-1,
      which is derived by restriction of built-in type nonNegativeInteger
      by facet maxExclusive with a value of: 1

</Notes>

<Instance  name="NISTXML-nonNegativeInteger-maxExclusive-1-1" href="NISTXML-nonNegativeInteger-maxExclusive-1-1.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-maxExclusive-1-1.xml
      XML instance number 1 in a series of 
      1 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-maxExclusive-1.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-nonNegativeInteger-maxExclusive-2" href="NISTSchema-nonNegativeInteger-maxExclusive-2.xsd">

<Notes>
      File: NISTSchema-nonNegativeInteger-maxExclusive-2.xsd
      This schema specifies a datatype, NISTSchema-nonNegativeInteger-maxExclusive-2,
      which is derived by restriction of built-in type nonNegativeInteger
      by facet maxExclusive with a value of: 93113652334413288257

</Notes>

<Instance  name="NISTXML-nonNegativeInteger-maxExclusive-2-1" href="NISTXML-nonNegativeInteger-maxExclusive-2-1.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-maxExclusive-2-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-maxExclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-maxExclusive-2-2" href="NISTXML-nonNegativeInteger-maxExclusive-2-2.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-maxExclusive-2-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-maxExclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-maxExclusive-2-3" href="NISTXML-nonNegativeInteger-maxExclusive-2-3.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-maxExclusive-2-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-maxExclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-maxExclusive-2-4" href="NISTXML-nonNegativeInteger-maxExclusive-2-4.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-maxExclusive-2-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-maxExclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-maxExclusive-2-5" href="NISTXML-nonNegativeInteger-maxExclusive-2-5.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-maxExclusive-2-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-maxExclusive-2.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-nonNegativeInteger-maxExclusive-3" href="NISTSchema-nonNegativeInteger-maxExclusive-3.xsd">

<Notes>
      File: NISTSchema-nonNegativeInteger-maxExclusive-3.xsd
      This schema specifies a datatype, NISTSchema-nonNegativeInteger-maxExclusive-3,
      which is derived by restriction of built-in type nonNegativeInteger
      by facet maxExclusive with a value of: 14738104862981882271

</Notes>

<Instance  name="NISTXML-nonNegativeInteger-maxExclusive-3-1" href="NISTXML-nonNegativeInteger-maxExclusive-3-1.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-maxExclusive-3-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-maxExclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-maxExclusive-3-2" href="NISTXML-nonNegativeInteger-maxExclusive-3-2.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-maxExclusive-3-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-maxExclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-maxExclusive-3-3" href="NISTXML-nonNegativeInteger-maxExclusive-3-3.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-maxExclusive-3-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-maxExclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-maxExclusive-3-4" href="NISTXML-nonNegativeInteger-maxExclusive-3-4.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-maxExclusive-3-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-maxExclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-maxExclusive-3-5" href="NISTXML-nonNegativeInteger-maxExclusive-3-5.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-maxExclusive-3-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-maxExclusive-3.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-nonNegativeInteger-maxExclusive-4" href="NISTSchema-nonNegativeInteger-maxExclusive-4.xsd">

<Notes>
      File: NISTSchema-nonNegativeInteger-maxExclusive-4.xsd
      This schema specifies a datatype, NISTSchema-nonNegativeInteger-maxExclusive-4,
      which is derived by restriction of built-in type nonNegativeInteger
      by facet maxExclusive with a value of: 16150080691773238684

</Notes>

<Instance  name="NISTXML-nonNegativeInteger-maxExclusive-4-1" href="NISTXML-nonNegativeInteger-maxExclusive-4-1.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-maxExclusive-4-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-maxExclusive-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-maxExclusive-4-2" href="NISTXML-nonNegativeInteger-maxExclusive-4-2.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-maxExclusive-4-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-maxExclusive-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-maxExclusive-4-3" href="NISTXML-nonNegativeInteger-maxExclusive-4-3.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-maxExclusive-4-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-maxExclusive-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-maxExclusive-4-4" href="NISTXML-nonNegativeInteger-maxExclusive-4-4.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-maxExclusive-4-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-maxExclusive-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-maxExclusive-4-5" href="NISTXML-nonNegativeInteger-maxExclusive-4-5.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-maxExclusive-4-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-maxExclusive-4.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-nonNegativeInteger-maxExclusive-5" href="NISTSchema-nonNegativeInteger-maxExclusive-5.xsd">

<Notes>
      File: NISTSchema-nonNegativeInteger-maxExclusive-5.xsd
      This schema specifies a datatype, NISTSchema-nonNegativeInteger-maxExclusive-5,
      which is derived by restriction of built-in type nonNegativeInteger
      by facet maxExclusive with a value of: 99999999999999999999

</Notes>

<Instance  name="NISTXML-nonNegativeInteger-maxExclusive-5-1" href="NISTXML-nonNegativeInteger-maxExclusive-5-1.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-maxExclusive-5-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-maxExclusive-5.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-maxExclusive-5-2" href="NISTXML-nonNegativeInteger-maxExclusive-5-2.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-maxExclusive-5-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-maxExclusive-5.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-maxExclusive-5-3" href="NISTXML-nonNegativeInteger-maxExclusive-5-3.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-maxExclusive-5-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-maxExclusive-5.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-maxExclusive-5-4" href="NISTXML-nonNegativeInteger-maxExclusive-5-4.xml">

<Notes>
      File: NISTXML-nonNegativeInteger-maxExclusive-5-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-nonNegativeInteger-maxExclusive-5.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-nonNegativeInteger-maxExclusive-5-5" href="NISTXML-nonNegativeInteger-maxExclusive-5-5.xml">

<Notes>