<?xml version="1.0"?>

<!DOCTYPE NISTXMLSchemaTypeTests [

<!ELEMENT NISTXMLSchemaTypeTests (Type)>

  <!ATTLIST NISTXMLSchemaTypeTests xml:base CDATA #REQUIRED>

<!ELEMENT Type (Notes, Facet*)>

  <!ATTLIST Type Name CDATA #REQUIRED>
  <!ATTLIST Type href CDATA #REQUIRED>

<!ELEMENT Notes (#PCDATA)>

<!ELEMENT Facet (Notes, Schema*)>

  <!ATTLIST Facet Name CDATA #REQUIRED>
  <!ATTLIST Facet href CDATA #REQUIRED>

<!ELEMENT Schema (Notes, Instance*)>

  <!ATTLIST Schema name CDATA #REQUIRED>
  <!ATTLIST Schema href CDATA #REQUIRED>

<!ELEMENT Instance (Notes)>

  <!ATTLIST Instance name CDATA #REQUIRED>
  <!ATTLIST Instance href CDATA #REQUIRED>

]>

<NISTXMLSchemaTypeTests xml:base="">

<Type Name="normalizedString" href="http://www.w3.org/TR/2001/REC-xmlschema-2-20010502/#normalizedString">

<Notes>
The value space of type normalizedString used in these tests is actually a
subset of that defined in the Recommendation. The local normalizedString
type behaves as if it were derived from the general type by restriction
with maxLength == 1000 and with a minLength == 0. 

This constraint applies to normalizedString and all its derivatives,
in the absence of further constraints.

</Notes>

<Facet Name="maxLength" href="http://www.w3.org/TR/2001/REC-xmlschema-2-20010502/#rf-maxLength">

<Notes>

</Notes>

<Schema  name="NISTSchema-normalizedString-maxLength-1" href="NISTSchema-normalizedString-maxLength-1.xsd">

<Notes>
      File: NISTSchema-normalizedString-maxLength-1.xsd
      This schema specifies a datatype, NISTSchema-normalizedString-maxLength-1,
      which is derived by restriction of built-in type normalizedString
      by facet maxLength with a value of: 0

</Notes>

<Instance  name="NISTXML-normalizedString-maxLength-1-1" href="NISTXML-normalizedString-maxLength-1-1.xml">

<Notes>
      File: NISTXML-normalizedString-maxLength-1-1.xml
      XML instance number 1 in a series of 
      1 conforming to NIST test schema
      NISTSchema-normalizedString-maxLength-1.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-normalizedString-maxLength-2" href="NISTSchema-normalizedString-maxLength-2.xsd">

<Notes>
      File: NISTSchema-normalizedString-maxLength-2.xsd
      This schema specifies a datatype, NISTSchema-normalizedString-maxLength-2,
      which is derived by restriction of built-in type normalizedString
      by facet maxLength with a value of: 548

</Notes>

<Instance  name="NISTXML-normalizedString-maxLength-2-1" href="NISTXML-normalizedString-maxLength-2-1.xml">

<Notes>
      File: NISTXML-normalizedString-maxLength-2-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-maxLength-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-maxLength-2-2" href="NISTXML-normalizedString-maxLength-2-2.xml">

<Notes>
      File: NISTXML-normalizedString-maxLength-2-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-maxLength-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-maxLength-2-3" href="NISTXML-normalizedString-maxLength-2-3.xml">

<Notes>
      File: NISTXML-normalizedString-maxLength-2-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-maxLength-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-maxLength-2-4" href="NISTXML-normalizedString-maxLength-2-4.xml">

<Notes>
      File: NISTXML-normalizedString-maxLength-2-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-maxLength-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-maxLength-2-5" href="NISTXML-normalizedString-maxLength-2-5.xml">

<Notes>
      File: NISTXML-normalizedString-maxLength-2-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-maxLength-2.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-normalizedString-maxLength-3" href="NISTSchema-normalizedString-maxLength-3.xsd">

<Notes>
      File: NISTSchema-normalizedString-maxLength-3.xsd
      This schema specifies a datatype, NISTSchema-normalizedString-maxLength-3,
      which is derived by restriction of built-in type normalizedString
      by facet maxLength with a value of: 319

</Notes>

<Instance  name="NISTXML-normalizedString-maxLength-3-1" href="NISTXML-normalizedString-maxLength-3-1.xml">

<Notes>
      File: NISTXML-normalizedString-maxLength-3-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-maxLength-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-maxLength-3-2" href="NISTXML-normalizedString-maxLength-3-2.xml">

<Notes>
      File: NISTXML-normalizedString-maxLength-3-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-maxLength-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-maxLength-3-3" href="NISTXML-normalizedString-maxLength-3-3.xml">

<Notes>
      File: NISTXML-normalizedString-maxLength-3-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-maxLength-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-maxLength-3-4" href="NISTXML-normalizedString-maxLength-3-4.xml">

<Notes>
      File: NISTXML-normalizedString-maxLength-3-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-maxLength-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-maxLength-3-5" href="NISTXML-normalizedString-maxLength-3-5.xml">

<Notes>
      File: NISTXML-normalizedString-maxLength-3-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-maxLength-3.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-normalizedString-maxLength-4" href="NISTSchema-normalizedString-maxLength-4.xsd">

<Notes>
      File: NISTSchema-normalizedString-maxLength-4.xsd
      This schema specifies a datatype, NISTSchema-normalizedString-maxLength-4,
      which is derived by restriction of built-in type normalizedString
      by facet maxLength with a value of: 630

</Notes>

<Instance  name="NISTXML-normalizedString-maxLength-4-1" href="NISTXML-normalizedString-maxLength-4-1.xml">

<Notes>
      File: NISTXML-normalizedString-maxLength-4-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-maxLength-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-maxLength-4-2" href="NISTXML-normalizedString-maxLength-4-2.xml">

<Notes>
      File: NISTXML-normalizedString-maxLength-4-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-maxLength-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-maxLength-4-3" href="NISTXML-normalizedString-maxLength-4-3.xml">

<Notes>
      File: NISTXML-normalizedString-maxLength-4-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-maxLength-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-maxLength-4-4" href="NISTXML-normalizedString-maxLength-4-4.xml">

<Notes>
      File: NISTXML-normalizedString-maxLength-4-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-maxLength-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-maxLength-4-5" href="NISTXML-normalizedString-maxLength-4-5.xml">

<Notes>
      File: NISTXML-normalizedString-maxLength-4-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-maxLength-4.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-normalizedString-maxLength-5" href="NISTSchema-normalizedString-maxLength-5.xsd">

<Notes>
      File: NISTSchema-normalizedString-maxLength-5.xsd
      This schema specifies a datatype, NISTSchema-normalizedString-maxLength-5,
      which is derived by restriction of built-in type normalizedString
      by facet maxLength with a value of: 1000

</Notes>

<Instance  name="NISTXML-normalizedString-maxLength-5-1" href="NISTXML-normalizedString-maxLength-5-1.xml">

<Notes>
      File: NISTXML-normalizedString-maxLength-5-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-maxLength-5.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-maxLength-5-2" href="NISTXML-normalizedString-maxLength-5-2.xml">

<Notes>
      File: NISTXML-normalizedString-maxLength-5-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-maxLength-5.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-maxLength-5-3" href="NISTXML-normalizedString-maxLength-5-3.xml">

<Notes>
      File: NISTXML-normalizedString-maxLength-5-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-maxLength-5.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-maxLength-5-4" href="NISTXML-normalizedString-maxLength-5-4.xml">

<Notes>
      File: NISTXML-normalizedString-maxLength-5-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-maxLength-5.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-maxLength-5-5" href="NISTXML-normalizedString-maxLength-5-5.xml">

<Notes>
      File: NISTXML-normalizedString-maxLength-5-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-maxLength-5.xsd.

</Notes>


</Instance>


</Schema>


</Facet>

<Facet Name="minLength" href="http://www.w3.org/TR/2001/REC-xmlschema-2-20010502/#rf-minLength">

<Notes>

</Notes>

<Schema  name="NISTSchema-normalizedString-minLength-1" href="NISTSchema-normalizedString-minLength-1.xsd">

<Notes>
      File: NISTSchema-normalizedString-minLength-1.xsd
      This schema specifies a datatype, NISTSchema-normalizedString-minLength-1,
      which is derived by restriction of built-in type normalizedString
      by facet minLength with a value of: 0

</Notes>

<Instance  name="NISTXML-normalizedString-minLength-1-1" href="NISTXML-normalizedString-minLength-1-1.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-1-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-1.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-minLength-1-2" href="NISTXML-normalizedString-minLength-1-2.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-1-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-1.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-minLength-1-3" href="NISTXML-normalizedString-minLength-1-3.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-1-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-1.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-minLength-1-4" href="NISTXML-normalizedString-minLength-1-4.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-1-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-1.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-minLength-1-5" href="NISTXML-normalizedString-minLength-1-5.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-1-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-1.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-normalizedString-minLength-2" href="NISTSchema-normalizedString-minLength-2.xsd">

<Notes>
      File: NISTSchema-normalizedString-minLength-2.xsd
      This schema specifies a datatype, NISTSchema-normalizedString-minLength-2,
      which is derived by restriction of built-in type normalizedString
      by facet minLength with a value of: 995

</Notes>

<Instance  name="NISTXML-normalizedString-minLength-2-1" href="NISTXML-normalizedString-minLength-2-1.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-2-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-minLength-2-2" href="NISTXML-normalizedString-minLength-2-2.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-2-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-minLength-2-3" href="NISTXML-normalizedString-minLength-2-3.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-2-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-minLength-2-4" href="NISTXML-normalizedString-minLength-2-4.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-2-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-minLength-2-5" href="NISTXML-normalizedString-minLength-2-5.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-2-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-2.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-normalizedString-minLength-3" href="NISTSchema-normalizedString-minLength-3.xsd">

<Notes>
      File: NISTSchema-normalizedString-minLength-3.xsd
      This schema specifies a datatype, NISTSchema-normalizedString-minLength-3,
      which is derived by restriction of built-in type normalizedString
      by facet minLength with a value of: 636

</Notes>

<Instance  name="NISTXML-normalizedString-minLength-3-1" href="NISTXML-normalizedString-minLength-3-1.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-3-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-minLength-3-2" href="NISTXML-normalizedString-minLength-3-2.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-3-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-minLength-3-3" href="NISTXML-normalizedString-minLength-3-3.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-3-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-minLength-3-4" href="NISTXML-normalizedString-minLength-3-4.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-3-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-minLength-3-5" href="NISTXML-normalizedString-minLength-3-5.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-3-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-3.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-normalizedString-minLength-4" href="NISTSchema-normalizedString-minLength-4.xsd">

<Notes>
      File: NISTSchema-normalizedString-minLength-4.xsd
      This schema specifies a datatype, NISTSchema-normalizedString-minLength-4,
      which is derived by restriction of built-in type normalizedString
      by facet minLength with a value of: 350

</Notes>

<Instance  name="NISTXML-normalizedString-minLength-4-1" href="NISTXML-normalizedString-minLength-4-1.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-4-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-minLength-4-2" href="NISTXML-normalizedString-minLength-4-2.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-4-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-minLength-4-3" href="NISTXML-normalizedString-minLength-4-3.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-4-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-minLength-4-4" href="NISTXML-normalizedString-minLength-4-4.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-4-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-minLength-4-5" href="NISTXML-normalizedString-minLength-4-5.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-4-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-4.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-normalizedString-minLength-5" href="NISTSchema-normalizedString-minLength-5.xsd">

<Notes>
      File: NISTSchema-normalizedString-minLength-5.xsd
      This schema specifies a datatype, NISTSchema-normalizedString-minLength-5,
      which is derived by restriction of built-in type normalizedString
      by facet minLength with a value of: 1000

</Notes>

<Instance  name="NISTXML-normalizedString-minLength-5-1" href="NISTXML-normalizedString-minLength-5-1.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-5-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-5.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-minLength-5-2" href="NISTXML-normalizedString-minLength-5-2.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-5-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-5.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-minLength-5-3" href="NISTXML-normalizedString-minLength-5-3.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-5-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-5.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-minLength-5-4" href="NISTXML-normalizedString-minLength-5-4.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-5-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-5.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-minLength-5-5" href="NISTXML-normalizedString-minLength-5-5.xml">

<Notes>
      File: NISTXML-normalizedString-minLength-5-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-minLength-5.xsd.

</Notes>


</Instance>


</Schema>


</Facet>

<Facet Name="length" href="http://www.w3.org/TR/2001/REC-xmlschema-2-20010502/#rf-length">

<Notes>

</Notes>

<Schema  name="NISTSchema-normalizedString-length-1" href="NISTSchema-normalizedString-length-1.xsd">

<Notes>
      File: NISTSchema-normalizedString-length-1.xsd
      This schema specifies a datatype, NISTSchema-normalizedString-length-1,
      which is derived by restriction of built-in type normalizedString
      by facet length with a value of: 0

</Notes>

<Instance  name="NISTXML-normalizedString-length-1-1" href="NISTXML-normalizedString-length-1-1.xml">

<Notes>
      File: NISTXML-normalizedString-length-1-1.xml
      XML instance number 1 in a series of 
      1 conforming to NIST test schema
      NISTSchema-normalizedString-length-1.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-normalizedString-length-2" href="NISTSchema-normalizedString-length-2.xsd">

<Notes>
      File: NISTSchema-normalizedString-length-2.xsd
      This schema specifies a datatype, NISTSchema-normalizedString-length-2,
      which is derived by restriction of built-in type normalizedString
      by facet length with a value of: 526

</Notes>

<Instance  name="NISTXML-normalizedString-length-2-1" href="NISTXML-normalizedString-length-2-1.xml">

<Notes>
      File: NISTXML-normalizedString-length-2-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-length-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-length-2-2" href="NISTXML-normalizedString-length-2-2.xml">

<Notes>
      File: NISTXML-normalizedString-length-2-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-length-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-length-2-3" href="NISTXML-normalizedString-length-2-3.xml">

<Notes>
      File: NISTXML-normalizedString-length-2-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-length-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-length-2-4" href="NISTXML-normalizedString-length-2-4.xml">

<Notes>
      File: NISTXML-normalizedString-length-2-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-length-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-length-2-5" href="NISTXML-normalizedString-length-2-5.xml">

<Notes>
      File: NISTXML-normalizedString-length-2-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-length-2.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-normalizedString-length-3" href="NISTSchema-normalizedString-length-3.xsd">

<Notes>
      File: NISTSchema-normalizedString-length-3.xsd
      This schema specifies a datatype, NISTSchema-normalizedString-length-3,
      which is derived by restriction of built-in type normalizedString
      by facet length with a value of: 895

</Notes>

<Instance  name="NISTXML-normalizedString-length-3-1" href="NISTXML-normalizedString-length-3-1.xml">

<Notes>
      File: NISTXML-normalizedString-length-3-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-length-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-length-3-2" href="NISTXML-normalizedString-length-3-2.xml">

<Notes>
      File: NISTXML-normalizedString-length-3-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-length-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-length-3-3" href="NISTXML-normalizedString-length-3-3.xml">

<Notes>
      File: NISTXML-normalizedString-length-3-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-length-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-length-3-4" href="NISTXML-normalizedString-length-3-4.xml">

<Notes>
      File: NISTXML-normalizedString-length-3-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-length-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-length-3-5" href="NISTXML-normalizedString-length-3-5.xml">

<Notes>
      File: NISTXML-normalizedString-length-3-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-length-3.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-normalizedString-length-4" href="NISTSchema-normalizedString-length-4.xsd">

<Notes>
      File: NISTSchema-normalizedString-length-4.xsd
      This schema specifies a datatype, NISTSchema-normalizedString-length-4,
      which is derived by restriction of built-in type normalizedString
      by facet length with a value of: 737

</Notes>

<Instance  name="NISTXML-normalizedString-length-4-1" href="NISTXML-normalizedString-length-4-1.xml">

<Notes>
      File: NISTXML-normalizedString-length-4-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-length-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-length-4-2" href="NISTXML-normalizedString-length-4-2.xml">

<Notes>
      File: NISTXML-normalizedString-length-4-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-length-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-length-4-3" href="NISTXML-normalizedString-length-4-3.xml">

<Notes>
      File: NISTXML-normalizedString-length-4-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-length-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-length-4-4" href="NISTXML-normalizedString-length-4-4.xml">

<Notes>
      File: NISTXML-normalizedString-length-4-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-length-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-length-4-5" href="NISTXML-normalizedString-length-4-5.xml">

<Notes>
      File: NISTXML-normalizedString-length-4-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-length-4.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-normalizedString-length-5" href="NISTSchema-normalizedString-length-5.xsd">

<Notes>
      File: NISTSchema-normalizedString-length-5.xsd
      This schema specifies a datatype, NISTSchema-normalizedString-length-5,
      which is derived by restriction of built-in type normalizedString
      by facet length with a value of: 1000

</Notes>

<Instance  name="NISTXML-normalizedString-length-5-1" href="NISTXML-normalizedString-length-5-1.xml">

<Notes>
      File: NISTXML-normalizedString-length-5-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-length-5.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-length-5-2" href="NISTXML-normalizedString-length-5-2.xml">

<Notes>
      File: NISTXML-normalizedString-length-5-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-length-5.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-length-5-3" href="NISTXML-normalizedString-length-5-3.xml">

<Notes>
      File: NISTXML-normalizedString-length-5-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-length-5.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-length-5-4" href="NISTXML-normalizedString-length-5-4.xml">

<Notes>
      File: NISTXML-normalizedString-length-5-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-length-5.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-normalizedString-length-5-5" href="NISTXML-normalizedString-length-5-5.xml">

<Notes>
      File: NISTXML-normalizedString-length-5-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-normalizedString-length-5.xsd.

</Notes>


</Instance>


</Schema>


</Facet>

<Facet Name="pattern" href="http://www.w3.org/TR/2001/REC-xmlschema-2-20010502/#rf-pattern">

<Notes>
The generalized regular expressions from which pattern specifications are derived
for the various types are as follows:

decimal::= \-?\d{0,t-f}(\.\d{1,f})?
	Where:
	\- is the optional negative sign
	\d is any digit (same as [0-9]);
 	\. represents the decimal point;
	t is the total number of digits in the string (ie the value of the totalDigits facet);
	f is the number of digits in the fractional part of the number (ie the value of
	the fractionDigits facet).
