<?xml version="1.0"?>

<!DOCTYPE NISTXMLSchemaTypeTests [

<!ELEMENT NISTXMLSchemaTypeTests (Type)>

  <!ATTLIST NISTXMLSchemaTypeTests xml:base CDATA #REQUIRED>

<!ELEMENT Type (Notes, Facet*)>

  <!ATTLIST Type Name CDATA #REQUIRED>
  <!ATTLIST Type href CDATA #REQUIRED>

<!ELEMENT Notes (#PCDATA)>

<!ELEMENT Facet (Notes, Schema*)>

  <!ATTLIST Facet Name CDATA #REQUIRED>
  <!ATTLIST Facet href CDATA #REQUIRED>

<!ELEMENT Schema (Notes, Instance*)>

  <!ATTLIST Schema name CDATA #REQUIRED>
  <!ATTLIST Schema href CDATA #REQUIRED>

<!ELEMENT Instance (Notes)>

  <!ATTLIST Instance name CDATA #REQUIRED>
  <!ATTLIST Instance href CDATA #REQUIRED>

]>

<NISTXMLSchemaTypeTests xml:base="">

<Type Name="short" href="http://www.w3.org/TR/2001/REC-xmlschema-2-20010502/#short">

<Notes>
This local type is as decribed in the Recommendation.

</Notes>

<Facet Name="minExclusive" href="http://www.w3.org/TR/2001/REC-xmlschema-2-20010502/#rf-minExclusive">

<Notes>

</Notes>

<Schema  name="NISTSchema-short-minExclusive-1" href="NISTSchema-short-minExclusive-1.xsd">

<Notes>
      File: NISTSchema-short-minExclusive-1.xsd
      This schema specifies a datatype, NISTSchema-short-minExclusive-1,
      which is derived by restriction of built-in type short
      by facet minExclusive with a value of: -32768

</Notes>

<Instance  name="NISTXML-short-minExclusive-1-1" href="NISTXML-short-minExclusive-1-1.xml">

<Notes>
      File: NISTXML-short-minExclusive-1-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minExclusive-1.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minExclusive-1-2" href="NISTXML-short-minExclusive-1-2.xml">

<Notes>
      File: NISTXML-short-minExclusive-1-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minExclusive-1.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minExclusive-1-3" href="NISTXML-short-minExclusive-1-3.xml">

<Notes>
      File: NISTXML-short-minExclusive-1-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minExclusive-1.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minExclusive-1-4" href="NISTXML-short-minExclusive-1-4.xml">

<Notes>
      File: NISTXML-short-minExclusive-1-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minExclusive-1.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minExclusive-1-5" href="NISTXML-short-minExclusive-1-5.xml">

<Notes>
      File: NISTXML-short-minExclusive-1-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minExclusive-1.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-short-minExclusive-2" href="NISTSchema-short-minExclusive-2.xsd">

<Notes>
      File: NISTSchema-short-minExclusive-2.xsd
      This schema specifies a datatype, NISTSchema-short-minExclusive-2,
      which is derived by restriction of built-in type short
      by facet minExclusive with a value of: 18601

</Notes>

<Instance  name="NISTXML-short-minExclusive-2-1" href="NISTXML-short-minExclusive-2-1.xml">

<Notes>
      File: NISTXML-short-minExclusive-2-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minExclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minExclusive-2-2" href="NISTXML-short-minExclusive-2-2.xml">

<Notes>
      File: NISTXML-short-minExclusive-2-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minExclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minExclusive-2-3" href="NISTXML-short-minExclusive-2-3.xml">

<Notes>
      File: NISTXML-short-minExclusive-2-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minExclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minExclusive-2-4" href="NISTXML-short-minExclusive-2-4.xml">

<Notes>
      File: NISTXML-short-minExclusive-2-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minExclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minExclusive-2-5" href="NISTXML-short-minExclusive-2-5.xml">

<Notes>
      File: NISTXML-short-minExclusive-2-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minExclusive-2.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-short-minExclusive-3" href="NISTSchema-short-minExclusive-3.xsd">

<Notes>
      File: NISTSchema-short-minExclusive-3.xsd
      This schema specifies a datatype, NISTSchema-short-minExclusive-3,
      which is derived by restriction of built-in type short
      by facet minExclusive with a value of: -2432

</Notes>

<Instance  name="NISTXML-short-minExclusive-3-1" href="NISTXML-short-minExclusive-3-1.xml">

<Notes>
      File: NISTXML-short-minExclusive-3-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minExclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minExclusive-3-2" href="NISTXML-short-minExclusive-3-2.xml">

<Notes>
      File: NISTXML-short-minExclusive-3-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minExclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minExclusive-3-3" href="NISTXML-short-minExclusive-3-3.xml">

<Notes>
      File: NISTXML-short-minExclusive-3-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minExclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minExclusive-3-4" href="NISTXML-short-minExclusive-3-4.xml">

<Notes>
      File: NISTXML-short-minExclusive-3-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minExclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minExclusive-3-5" href="NISTXML-short-minExclusive-3-5.xml">

<Notes>
      File: NISTXML-short-minExclusive-3-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minExclusive-3.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-short-minExclusive-4" href="NISTSchema-short-minExclusive-4.xsd">

<Notes>
      File: NISTSchema-short-minExclusive-4.xsd
      This schema specifies a datatype, NISTSchema-short-minExclusive-4,
      which is derived by restriction of built-in type short
      by facet minExclusive with a value of: -29760

</Notes>

<Instance  name="NISTXML-short-minExclusive-4-1" href="NISTXML-short-minExclusive-4-1.xml">

<Notes>
      File: NISTXML-short-minExclusive-4-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minExclusive-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minExclusive-4-2" href="NISTXML-short-minExclusive-4-2.xml">

<Notes>
      File: NISTXML-short-minExclusive-4-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minExclusive-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minExclusive-4-3" href="NISTXML-short-minExclusive-4-3.xml">

<Notes>
      File: NISTXML-short-minExclusive-4-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minExclusive-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minExclusive-4-4" href="NISTXML-short-minExclusive-4-4.xml">

<Notes>
      File: NISTXML-short-minExclusive-4-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minExclusive-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minExclusive-4-5" href="NISTXML-short-minExclusive-4-5.xml">

<Notes>
      File: NISTXML-short-minExclusive-4-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minExclusive-4.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-short-minExclusive-5" href="NISTSchema-short-minExclusive-5.xsd">

<Notes>
      File: NISTSchema-short-minExclusive-5.xsd
      This schema specifies a datatype, NISTSchema-short-minExclusive-5,
      which is derived by restriction of built-in type short
      by facet minExclusive with a value of: 32766

</Notes>

<Instance  name="NISTXML-short-minExclusive-5-1" href="NISTXML-short-minExclusive-5-1.xml">

<Notes>
      File: NISTXML-short-minExclusive-5-1.xml
      XML instance number 1 in a series of 
      1 conforming to NIST test schema
      NISTSchema-short-minExclusive-5.xsd.

</Notes>


</Instance>


</Schema>


</Facet>

<Facet Name="minInclusive" href="http://www.w3.org/TR/2001/REC-xmlschema-2-20010502/#rf-minInclusive">

<Notes>

</Notes>

<Schema  name="NISTSchema-short-minInclusive-1" href="NISTSchema-short-minInclusive-1.xsd">

<Notes>
      File: NISTSchema-short-minInclusive-1.xsd
      This schema specifies a datatype, NISTSchema-short-minInclusive-1,
      which is derived by restriction of built-in type short
      by facet minInclusive with a value of: -32768

</Notes>

<Instance  name="NISTXML-short-minInclusive-1-1" href="NISTXML-short-minInclusive-1-1.xml">

<Notes>
      File: NISTXML-short-minInclusive-1-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minInclusive-1.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minInclusive-1-2" href="NISTXML-short-minInclusive-1-2.xml">

<Notes>
      File: NISTXML-short-minInclusive-1-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minInclusive-1.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minInclusive-1-3" href="NISTXML-short-minInclusive-1-3.xml">

<Notes>
      File: NISTXML-short-minInclusive-1-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minInclusive-1.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minInclusive-1-4" href="NISTXML-short-minInclusive-1-4.xml">

<Notes>
      File: NISTXML-short-minInclusive-1-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minInclusive-1.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minInclusive-1-5" href="NISTXML-short-minInclusive-1-5.xml">

<Notes>
      File: NISTXML-short-minInclusive-1-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minInclusive-1.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-short-minInclusive-2" href="NISTSchema-short-minInclusive-2.xsd">

<Notes>
      File: NISTSchema-short-minInclusive-2.xsd
      This schema specifies a datatype, NISTSchema-short-minInclusive-2,
      which is derived by restriction of built-in type short
      by facet minInclusive with a value of: 17388

</Notes>

<Instance  name="NISTXML-short-minInclusive-2-1" href="NISTXML-short-minInclusive-2-1.xml">

<Notes>
      File: NISTXML-short-minInclusive-2-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minInclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minInclusive-2-2" href="NISTXML-short-minInclusive-2-2.xml">

<Notes>
      File: NISTXML-short-minInclusive-2-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minInclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minInclusive-2-3" href="NISTXML-short-minInclusive-2-3.xml">

<Notes>
      File: NISTXML-short-minInclusive-2-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minInclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minInclusive-2-4" href="NISTXML-short-minInclusive-2-4.xml">

<Notes>
      File: NISTXML-short-minInclusive-2-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minInclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minInclusive-2-5" href="NISTXML-short-minInclusive-2-5.xml">

<Notes>
      File: NISTXML-short-minInclusive-2-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minInclusive-2.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-short-minInclusive-3" href="NISTSchema-short-minInclusive-3.xsd">

<Notes>
      File: NISTSchema-short-minInclusive-3.xsd
      This schema specifies a datatype, NISTSchema-short-minInclusive-3,
      which is derived by restriction of built-in type short
      by facet minInclusive with a value of: 30223

</Notes>

<Instance  name="NISTXML-short-minInclusive-3-1" href="NISTXML-short-minInclusive-3-1.xml">

<Notes>
      File: NISTXML-short-minInclusive-3-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minInclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minInclusive-3-2" href="NISTXML-short-minInclusive-3-2.xml">

<Notes>
      File: NISTXML-short-minInclusive-3-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minInclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minInclusive-3-3" href="NISTXML-short-minInclusive-3-3.xml">

<Notes>
      File: NISTXML-short-minInclusive-3-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minInclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minInclusive-3-4" href="NISTXML-short-minInclusive-3-4.xml">

<Notes>
      File: NISTXML-short-minInclusive-3-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minInclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minInclusive-3-5" href="NISTXML-short-minInclusive-3-5.xml">

<Notes>
      File: NISTXML-short-minInclusive-3-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minInclusive-3.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-short-minInclusive-4" href="NISTSchema-short-minInclusive-4.xsd">

<Notes>
      File: NISTSchema-short-minInclusive-4.xsd
      This schema specifies a datatype, NISTSchema-short-minInclusive-4,
      which is derived by restriction of built-in type short
      by facet minInclusive with a value of: 30224

</Notes>

<Instance  name="NISTXML-short-minInclusive-4-1" href="NISTXML-short-minInclusive-4-1.xml">

<Notes>
      File: NISTXML-short-minInclusive-4-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minInclusive-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minInclusive-4-2" href="NISTXML-short-minInclusive-4-2.xml">

<Notes>
      File: NISTXML-short-minInclusive-4-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minInclusive-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minInclusive-4-3" href="NISTXML-short-minInclusive-4-3.xml">

<Notes>
      File: NISTXML-short-minInclusive-4-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minInclusive-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minInclusive-4-4" href="NISTXML-short-minInclusive-4-4.xml">

<Notes>
      File: NISTXML-short-minInclusive-4-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minInclusive-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-minInclusive-4-5" href="NISTXML-short-minInclusive-4-5.xml">

<Notes>
      File: NISTXML-short-minInclusive-4-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-minInclusive-4.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-short-minInclusive-5" href="NISTSchema-short-minInclusive-5.xsd">

<Notes>
      File: NISTSchema-short-minInclusive-5.xsd
      This schema specifies a datatype, NISTSchema-short-minInclusive-5,
      which is derived by restriction of built-in type short
      by facet minInclusive with a value of: 32767

</Notes>

<Instance  name="NISTXML-short-minInclusive-5-1" href="NISTXML-short-minInclusive-5-1.xml">

<Notes>
      File: NISTXML-short-minInclusive-5-1.xml
      XML instance number 1 in a series of 
      1 conforming to NIST test schema
      NISTSchema-short-minInclusive-5.xsd.

</Notes>


</Instance>


</Schema>


</Facet>

<Facet Name="maxExclusive" href="http://www.w3.org/TR/2001/REC-xmlschema-2-20010502/#rf-maxExclusive">

<Notes>

</Notes>

<Schema  name="NISTSchema-short-maxExclusive-1" href="NISTSchema-short-maxExclusive-1.xsd">

<Notes>
      File: NISTSchema-short-maxExclusive-1.xsd
      This schema specifies a datatype, NISTSchema-short-maxExclusive-1,
      which is derived by restriction of built-in type short
      by facet maxExclusive with a value of: -32767

</Notes>

<Instance  name="NISTXML-short-maxExclusive-1-1" href="NISTXML-short-maxExclusive-1-1.xml">

<Notes>
      File: NISTXML-short-maxExclusive-1-1.xml
      XML instance number 1 in a series of 
      1 conforming to NIST test schema
      NISTSchema-short-maxExclusive-1.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-short-maxExclusive-2" href="NISTSchema-short-maxExclusive-2.xsd">

<Notes>
      File: NISTSchema-short-maxExclusive-2.xsd
      This schema specifies a datatype, NISTSchema-short-maxExclusive-2,
      which is derived by restriction of built-in type short
      by facet maxExclusive with a value of: -24968

</Notes>

<Instance  name="NISTXML-short-maxExclusive-2-1" href="NISTXML-short-maxExclusive-2-1.xml">

<Notes>
      File: NISTXML-short-maxExclusive-2-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxExclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-maxExclusive-2-2" href="NISTXML-short-maxExclusive-2-2.xml">

<Notes>
      File: NISTXML-short-maxExclusive-2-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxExclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-maxExclusive-2-3" href="NISTXML-short-maxExclusive-2-3.xml">

<Notes>
      File: NISTXML-short-maxExclusive-2-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxExclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-maxExclusive-2-4" href="NISTXML-short-maxExclusive-2-4.xml">

<Notes>
      File: NISTXML-short-maxExclusive-2-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxExclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-maxExclusive-2-5" href="NISTXML-short-maxExclusive-2-5.xml">

<Notes>
      File: NISTXML-short-maxExclusive-2-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxExclusive-2.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-short-maxExclusive-3" href="NISTSchema-short-maxExclusive-3.xsd">

<Notes>
      File: NISTSchema-short-maxExclusive-3.xsd
      This schema specifies a datatype, NISTSchema-short-maxExclusive-3,
      which is derived by restriction of built-in type short
      by facet maxExclusive with a value of: 23450

</Notes>

<Instance  name="NISTXML-short-maxExclusive-3-1" href="NISTXML-short-maxExclusive-3-1.xml">

<Notes>
      File: NISTXML-short-maxExclusive-3-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxExclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-maxExclusive-3-2" href="NISTXML-short-maxExclusive-3-2.xml">

<Notes>
      File: NISTXML-short-maxExclusive-3-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxExclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-maxExclusive-3-3" href="NISTXML-short-maxExclusive-3-3.xml">

<Notes>
      File: NISTXML-short-maxExclusive-3-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxExclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-maxExclusive-3-4" href="NISTXML-short-maxExclusive-3-4.xml">

<Notes>
      File: NISTXML-short-maxExclusive-3-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxExclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-maxExclusive-3-5" href="NISTXML-short-maxExclusive-3-5.xml">

<Notes>
      File: NISTXML-short-maxExclusive-3-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxExclusive-3.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-short-maxExclusive-4" href="NISTSchema-short-maxExclusive-4.xsd">

<Notes>
      File: NISTSchema-short-maxExclusive-4.xsd
      This schema specifies a datatype, NISTSchema-short-maxExclusive-4,
      which is derived by restriction of built-in type short
      by facet maxExclusive with a value of: -23419

</Notes>

<Instance  name="NISTXML-short-maxExclusive-4-1" href="NISTXML-short-maxExclusive-4-1.xml">

<Notes>
      File: NISTXML-short-maxExclusive-4-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxExclusive-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-maxExclusive-4-2" href="NISTXML-short-maxExclusive-4-2.xml">

<Notes>
      File: NISTXML-short-maxExclusive-4-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxExclusive-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-maxExclusive-4-3" href="NISTXML-short-maxExclusive-4-3.xml">

<Notes>
      File: NISTXML-short-maxExclusive-4-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxExclusive-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-maxExclusive-4-4" href="NISTXML-short-maxExclusive-4-4.xml">

<Notes>
      File: NISTXML-short-maxExclusive-4-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxExclusive-4.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-maxExclusive-4-5" href="NISTXML-short-maxExclusive-4-5.xml">

<Notes>
      File: NISTXML-short-maxExclusive-4-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxExclusive-4.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-short-maxExclusive-5" href="NISTSchema-short-maxExclusive-5.xsd">

<Notes>
      File: NISTSchema-short-maxExclusive-5.xsd
      This schema specifies a datatype, NISTSchema-short-maxExclusive-5,
      which is derived by restriction of built-in type short
      by facet maxExclusive with a value of: 32767

</Notes>

<Instance  name="NISTXML-short-maxExclusive-5-1" href="NISTXML-short-maxExclusive-5-1.xml">

<Notes>
      File: NISTXML-short-maxExclusive-5-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxExclusive-5.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-maxExclusive-5-2" href="NISTXML-short-maxExclusive-5-2.xml">

<Notes>
      File: NISTXML-short-maxExclusive-5-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxExclusive-5.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-maxExclusive-5-3" href="NISTXML-short-maxExclusive-5-3.xml">

<Notes>
      File: NISTXML-short-maxExclusive-5-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxExclusive-5.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-maxExclusive-5-4" href="NISTXML-short-maxExclusive-5-4.xml">

<Notes>
      File: NISTXML-short-maxExclusive-5-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxExclusive-5.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-maxExclusive-5-5" href="NISTXML-short-maxExclusive-5-5.xml">

<Notes>
      File: NISTXML-short-maxExclusive-5-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxExclusive-5.xsd.

</Notes>


</Instance>


</Schema>


</Facet>

<Facet Name="maxInclusive" href="http://www.w3.org/TR/2001/REC-xmlschema-2-20010502/#rf-maxInclusive">

<Notes>

</Notes>

<Schema  name="NISTSchema-short-maxInclusive-1" href="NISTSchema-short-maxInclusive-1.xsd">

<Notes>
      File: NISTSchema-short-maxInclusive-1.xsd
      This schema specifies a datatype, NISTSchema-short-maxInclusive-1,
      which is derived by restriction of built-in type short
      by facet maxInclusive with a value of: -32768

</Notes>

<Instance  name="NISTXML-short-maxInclusive-1-1" href="NISTXML-short-maxInclusive-1-1.xml">

<Notes>
      File: NISTXML-short-maxInclusive-1-1.xml
      XML instance number 1 in a series of 
      1 conforming to NIST test schema
      NISTSchema-short-maxInclusive-1.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-short-maxInclusive-2" href="NISTSchema-short-maxInclusive-2.xsd">

<Notes>
      File: NISTSchema-short-maxInclusive-2.xsd
      This schema specifies a datatype, NISTSchema-short-maxInclusive-2,
      which is derived by restriction of built-in type short
      by facet maxInclusive with a value of: 17144

</Notes>

<Instance  name="NISTXML-short-maxInclusive-2-1" href="NISTXML-short-maxInclusive-2-1.xml">

<Notes>
      File: NISTXML-short-maxInclusive-2-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxInclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-maxInclusive-2-2" href="NISTXML-short-maxInclusive-2-2.xml">

<Notes>
      File: NISTXML-short-maxInclusive-2-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxInclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-maxInclusive-2-3" href="NISTXML-short-maxInclusive-2-3.xml">

<Notes>
      File: NISTXML-short-maxInclusive-2-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxInclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-maxInclusive-2-4" href="NISTXML-short-maxInclusive-2-4.xml">

<Notes>
      File: NISTXML-short-maxInclusive-2-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxInclusive-2.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-maxInclusive-2-5" href="NISTXML-short-maxInclusive-2-5.xml">

<Notes>
      File: NISTXML-short-maxInclusive-2-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxInclusive-2.xsd.

</Notes>


</Instance>


</Schema>

<Schema  name="NISTSchema-short-maxInclusive-3" href="NISTSchema-short-maxInclusive-3.xsd">

<Notes>
      File: NISTSchema-short-maxInclusive-3.xsd
      This schema specifies a datatype, NISTSchema-short-maxInclusive-3,
      which is derived by restriction of built-in type short
      by facet maxInclusive with a value of: 10770

</Notes>

<Instance  name="NISTXML-short-maxInclusive-3-1" href="NISTXML-short-maxInclusive-3-1.xml">

<Notes>
      File: NISTXML-short-maxInclusive-3-1.xml
      XML instance number 1 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxInclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-maxInclusive-3-2" href="NISTXML-short-maxInclusive-3-2.xml">

<Notes>
      File: NISTXML-short-maxInclusive-3-2.xml
      XML instance number 2 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxInclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-maxInclusive-3-3" href="NISTXML-short-maxInclusive-3-3.xml">

<Notes>
      File: NISTXML-short-maxInclusive-3-3.xml
      XML instance number 3 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxInclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-maxInclusive-3-4" href="NISTXML-short-maxInclusive-3-4.xml">

<Notes>
      File: NISTXML-short-maxInclusive-3-4.xml
      XML instance number 4 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxInclusive-3.xsd.

</Notes>


</Instance>

<Instance  name="NISTXML-short-maxInclusive-3-5" href="NISTXML-short-maxInclusive-3-5.xml">

<Notes>
      File: NISTXML-short-maxInclusive-3-5.xml
      XML instance number 5 in a series of 
      5 conforming to NIST test schema
      NISTSchema-short-maxInclusive-3.xsd.

</Notes>


</Instance>


</Schema>
